name: tekartik_app_io_sqflite
description: Sqflite common initialization for io app
version: 0.5.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  sqflite_common_ffi: ">=2.3.4"
  sqflite_common: '>=2.0.0+1'
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
resolution: workspace
