# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "packages/app_launcher"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/app_platform"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/app_prefs"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/app_secure_env"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/app_sembast"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/app_sqflite"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/app_zip"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/example/sqflite_test_app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "repo_support"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
