name: tekartik_app_io_sembast
description: Sembast for io
version: 0.5.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  sembast: '>=3.0.0+2'
  sembast_sqflite: '>=2.0.0'
  path:
  tekartik_app_io_sqflite:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_sqflite
    version: '>=0.5.0'
  sqflite_common_ffi: 
dev_dependencies:
  dev_test:
  process_run:
  test:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
  tekartik_app_io_sqflite:
    path: ../app_sqflite
