name: tekartik_app_io_sembast
description: Sembast for io
version: 0.5.1
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  sembast: '>=3.0.0+2'
  sembast_sqflite: '>=2.0.0'
  path:
  tekartik_app_io_sqflite:
    git:
      url: git://github.com/tekartik/app_io_utils.dart
      ref: null_safety
      path: app_sqflite
    version: '>=0.5.0'

dev_dependencies:
  dev_test:
  pedantic:
  process_run:
  test:

dependency_overrides:
  tekartik_app_io_sqflite:
    path: ../app_sqflite
