name: tekartik_app_io_sqflite_test_app
description: Sqflite test app lib
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_io
    version: '>=0.2.3'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.2.3'
  tekartik_app_io_sqflite:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart3a
      path: packages/app_sqflite
    version: '>=0.1.0'
  tekartik_app_io_platform:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart3a
      path: packages/app_platform
    version: '>=0.1.0'
dev_dependencies:
  dev_build: ">=1.1.2"


_tmp_dependency_overrides:
  # temp offline
  tekartik_test_menu_io:
    path: ../../../../test_menu.dart/test_menu_io
  tekartik_test_menu:
    path: ../../../../test_menu.dart/test_menu
  tekartik_common_utils:
    path: ../../../../common_utils.dart
  tekartik_platform_io:
    path: ../../../../platform.dart/platform_io
  tekartik_platform:
    path: ../../../../platform.dart/platform
resolution: workspace
