name: tekartik_app_io_launcher
description: App io launcher (notepad, chrome, file explorer)
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  path: '>=1.8.0'
  process_run:

dev_dependencies:
  test: '>=1.16.0'
  dev_build: ">=1.0.1"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
  tekaly_assets:
    git:
      url: https://github.com/tekartikprj/tekaly.git
      ref: dart3a
      path: packages/tekaly_assets
