name: tekartik_app_io_launcher
description: App io launcher (notepad, chrome, file explorer)
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  path: ^1.8.0
  process_run:

dev_dependencies:
  test: ^1.16.0
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'
