name: tekartik_app_io_prefs
description: Prefs helper
version: 0.4.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  tekartik_app_io_sqflite:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      path: packages/app_sqflite
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_prefs_sembast:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_sembast
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart2_3
    version: '>=0.1.0'
  path:
  sembast:
  process_run:

dev_dependencies:
  dev_test:
  test:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
  tekartik_app_io_sqflite:
    path: ../app_sqflite
_tmp_dependency_overrides:
  # temp dev
  tekartik_prefs_sembast:
    path: ../../../prefs.dart/prefs_sembast
  tekartik_prefs:
    path: ../../../prefs.dart/prefs
  tekartik_common_utils:
    path: ../../../common_utils.dart
