name: tekartik_app_io_prefs
description: Prefs helper
version: 0.4.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_app_io_sqflite:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      path: packages/app_sqflite
      ref: dart3a
    version: '>=0.1.0'
  tekartik_prefs_sembast:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_sembast
      ref: dart3a
    version: '>=0.1.0'
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
      ref: dart3a
    version: '>=0.1.0'
  path: ">=1.9.0"
  sembast: ">=3.7.4+3"
  process_run: ">=1.2.1+1"

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

_tmp_dependency_overrides:
  # temp dev
  tekartik_prefs_sembast:
    path: ../../../prefs.dart/prefs_sembast
  tekartik_prefs:
    path: ../../../prefs.dart/prefs
  tekartik_common_utils:
    path: ../../../common_utils.dart
resolution: workspace
