name: tekartik_app_secure_env
description: A sample command-line application.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  process_run:
  tekartik_app_crypto:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_crypto
    version: '>=0.2.2'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'