name: tekartik_app_io_platform
description: Platform helper
version: 0.3.1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform_io
    version: '>=0.1.0'
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform
    version: '>=0.1.0'
dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
resolution: workspace
