name: tekartik_app_io_platform
description: Platform helper
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path:
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      ref: null_safety
      path: platform_io

dev_dependencies:
  process_run:
  test:

dependency_overrides:
