name: tekartik_app_io_platform
description: Platform helper
version: 0.3.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  path:
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart2_3
      path: platform_io
    version: '>=0.1.0'
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart2_3
      path: platform
    version: '>=0.1.0'
dev_dependencies:
  process_run:
  test:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
