name: app_io_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  path:
  dev_build:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
